### ISSUE TITLE
Startup failure: could not find CSS file

### ISSUE THREAD

**Issue by savchenko** [ErikReider/SwaySettings#26]
Compiled 2c8ebb8 with the default flags:

```gdb
[New Thread 0x7ffff34d1700 (LWP 93097)]
[New Thread 0x7ffff2cd0700 (LWP 93098)]
[New Thread 0x7ffff24cf700 (LWP 93099)]
[New Thread 0x7ffff1cbd700 (LWP 93100)]
COULD NOT FIND CSS FILE! REINSTALL THE PACKAGE! <-- here
[Thread 0x7ffff1cbd700 (LWP 93100) exited]
[Thread 0x7ffff24cf700 (LWP 93099) exited]
[Thread 0x7ffff34d1700 (LWP 93097) exited]
[Thread 0x7ffff37bba80 (LWP 93093) exited]
[Inferior 1 (process 93093) exited with code 01]
```

**Comment by ErikReider** [comment]
This seems to be that meson doesn't copy the .css file when building even if this line is present in the meson.build. It works when running `makepkg -s` but not when running `meson install` for some reason
https://github.com/ErikReider/SwaySettings/blob/2c8ebb8fed6b128e0ab6810e451c341003942609/src/meson.build#L52

**Comment by ErikReider** [comment]
Removed the css file 1493c26d23706e55c8cae2f500c7619df9c617f3

**Comment by savchenko** [comment]
![12-Nov_01-29-04](https://user-images.githubusercontent.com/300146/141319871-d79bd2ee-8cc8-411f-8622-320c8dc0f8f4.png)

:-)
