### ISSUE TITLE
Users section throws an exception

### ISSUE THREAD

**Issue by savchenko** [ErikReider/SwaySettings#27]
Launch and watch stderr. Open "Users" section:
```
./swaysettings

(swaysettings:114143): accountsservice-WARNING **: 01:31:11.639: ActUserManager: user (null) has no username (uid: -1)

(swaysettings:114143): Gtk-CRITICAL **: 01:31:11.639: gtk_entry_set_text: assertion 'text != NULL' failed
```

**Comment by ErikReider** [comment]
I'm not seeing this issue. What's your uid? (Bash: `id $USER`)

![image](https://user-images.githubusercontent.com/35975961/141335585-f10f9bcc-1c44-4999-8830-de29f3d0fcad.png)

**Comment by savchenko** [comment]
1000

**Comment by ErikReider** [comment]
Do you have `accountsservice` installed?

**Comment by savchenko** [comment]
Nope.

**Comment by ErikReider** [comment]
Oh. Try installing it

**Comment by ErikReider** [comment]
Tried it in a Ubuntu VM and it works for me. Try installing `libaccountsservice-dev` and `accountsservice`

**Comment by ErikReider** [comment]
Closing this issue. Feel free to comment if you're still experiencing this issue
