### ISSUE TITLE
More theme settings

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwaySettings#3]
- [x] Cursor theme

**Comment by ProjectInfinity** [comment]
Any update on this? I would love to be able to configure all of this from SwaySettings as it is currently quite cumbersome.

**Comment by ErikReider** [comment]
@ProjectInfinity The QT settings could be pretty cumbersome. The other GTK settings should be pretty "easy" to implement though

**Comment by ErikReider** [comment]
@ProjectInfinity I've now added a GTK cursor selector. Is there anything else that I'm missing?
