### ISSUE TITLE
`accountsservice' not found despite being installed

### ISSUE THREAD

**Issue by darthdubu** [ErikReider/SwaySettings#36]
Hey just want to say this project is a lifesaver and I loved it on Arch. Switched to Void Linux a few weeks ago and haven't had any luck compiling this here. I referenced the aur package to see what dependencies it needs and believe I have them all.
![image](https://user-images.githubusercontent.com/63337938/182481602-34d0362f-6161-4732-9446-c1495f1b1f4d.png)

However when I try to compile it it fails saying I don't have accountservice. Except I do. So I'm unsure what to do here.
![image](https://user-images.githubusercontent.com/63337938/182481774-0cee0824-433c-46bc-a640-db4fd0817f59.png)

![image](https://user-images.githubusercontent.com/63337938/182481711-aacd8f08-8e36-4928-be34-60e4ec0c4e39.png)

**Comment by ErikReider** [comment]
Seems like your accountsservice is very old? Mine is using version `22.08.0`
![image](https://user-images.githubusercontent.com/35975961/182588012-b062dc29-60a5-4f6f-a7ec-0e4ba8826cad.png)

The accountsservice needs to provide a gir or vapi file for it to work. Mine is provided by the package and is located at `/usr/share/gir-1.0/AccountsService-1.0.gir` and `/usr/share/vala/vapi/accountsservice.vapi` on Arch.

**Comment by raaffaaeell** [comment]
Yeah, I'm having this on latest fedora and cant figure out this dependency. I have `/usr/share/gir-1.0/AccountsService-1.0.gir`, but not the other one

**Comment by ErikReider** [comment]
Hmmm. Then I'll maybe have to include the vapi file in the repo like before... I'm on vacation this week so I'll fix this when I get back :)

**Comment by ErikReider** [comment]
So @raaffaaeell and @darthdubu, your accountsservice versions were released in 2019 and were the latest releases until early this year which is why it's so "outdated".
![image](https://user-images.githubusercontent.com/35975961/184672817-534e84ba-1645-4ea7-b809-c48b6ac1fe64.png)

Version `22.04.62` added support for vala bindings which is why it won't compile for you

**Comment by ErikReider** [comment]
Does #37 compile?

**Comment by raaffaaeell** [comment]
Will test later today and check back at you

**Comment by darthdubu** [comment]
it didn't for me
![image](https://user-images.githubusercontent.com/63337938/184709218-4802ae8a-2061-417e-a27c-f9a878fa13bd.png)

**Comment by darthdubu** [comment]
and i'm unable to compile a newer version of accountsservice because it apparently requires systemd to build. despite me having it installed from the Void Linux repos.
![image](https://user-images.githubusercontent.com/63337938/184710476-a108ade6-38e7-4340-b676-a38819039fa0.png)

**Comment by ErikReider** [comment]
> and i'm unable to compile a newer version of accountsservice because it apparently requires systemd to build. despite me having it installed from the Void Linux repos.
> ![image](https://user-images.githubusercontent.com/63337938/184710476-a108ade6-38e7-4340-b676-a38819039fa0.png)
> 

I'm not very familiar with void Linux but sometimes distros package the libs in a separate package like accountsservice-dev on Debian based distros

**Comment by darthdubu** [comment]
no no sorry. i may have misworded that. Void Linux doesn't use systemd. It uses runit. But it seems like you can disable that dependency i'm just not sure how.

**Comment by ErikReider** [comment]
Ooooh. Sorry, my bad. I can add it as a optional build option :)

I'm using systemd so I don't really know of any alternatives and if I did, it would be difficult to test :/

**Comment by darthdubu** [comment]
That'd be cool. I think theres supposed to be a way to pass a flag to tell it to disable that dependency but i couldn't find anything. I saw people discussing it in an issue but no luck. If you could make it optional that would help people who use distros that don't use systemd (gentoo, void, artix, devuan)

**Comment by darthdubu** [comment]
actually no what am i saying. i'm sorry this is kind of mess. i'm talking about the accountsservice package. not SwaySettings.

**Comment by darthdubu** [comment]
i simply just may not be able to use this on Void. hopefully the other guy has better luck.

**Comment by ErikReider** [comment]
Disabling the systemd usage when not running systemd would be the best option going forward but if that's not feasible, disabling the account page should also work

**Comment by darthdubu** [comment]
:pray: I'll leave it up to you. Sorry for the trouble. This is purely just a side-effect of using less common distros. I used your tool on Arch and it worked great.

**Comment by raaffaaeell** [comment]
For me, still doesnt work, I'm getting these errors

![image](https://user-images.githubusercontent.com/6959662/184756287-3da8a481-fce7-40a0-973b-82a08320bae7.png)

Similar to the other messages, but my brain cant make much sense of it

**Comment by darthdubu** [comment]
Hey it works now. I was way overthinking this one. I was able to get accountsservice to compile following these instructions and then compile SwaySettings without any issue.
https://www.linuxfromscratch.org/blfs/view/svn/general/accountsservice.html
@raaffaaeell You should be able to do the same. This issue is 100% related to the version of accountsservice you are running.

![image](https://user-images.githubusercontent.com/63337938/185237018-72dc716e-8101-4249-b84a-4ba5901f24a1.png)

**Comment by darthdubu** [comment]
Thanks for you help btw @ErikReider you rock and i'm sorry for wasting your time.

**Comment by ErikReider** [comment]
@raaffaaeell Can you open a new issue for building on Fedora?

**Comment by ErikReider** [comment]
@darthdubu Don't worry about it! :)

**Comment by darthdubu** [comment]
> @raaffaaeell Can you open a new issue for building on Fedora?

He likely won't need to. I checked Fedora repo and he has the exact same version as well. This is a distro agnostic problem.
![image](https://user-images.githubusercontent.com/63337938/185238259-2af1cfcc-97d5-405f-b07a-b3d8f4a98ad9.png)

**Comment by darthdubu** [comment]
But goodluck to other guy! I hope it works for you too :dancers:

**Comment by raaffaaeell** [comment]
Hello, you can leave this closed and I'll try to follow these new instructions yes, thanks for the help guys
