### ISSUE TITLE
[Feature request] Support other wlroots-based WM

### ISSUE THREAD

**Issue by werdahias** [ErikReider/SwaySettings#39]
I run Hyprland on debian. I built a quick debian package for sway-settings. When I try to launch it I get the following error:
```

swaysettings 
COULD NOT FIND SWAY SOCKET ENVIRONMENT VARIABLE!!!
```
Obviously this is because there is no sway socket running but a Hyprland one. I'd appreciate it if you could add support for it.

**Comment by ErikReider** [comment]
It would be too much work to maintain two separate systems. I'd consider swapping it out for a wlroots generic one that works on all WMs though. That would make my life a lot easier :)

I'm not even sure if there is such a thing though...

**Comment by werdahias** [comment]
thanks, appreciate the thought. If it was built on top of `wlroots` it should work on all wayland WMs. `sway-notification-center`  also works on Hyprland, for instance.

**Comment by ErikReider** [comment]
Swaync uses dbus while swaysettings parses sway-ipc for mouse and keyboard settings
