### ISSUE TITLE
Fresh install doesn't work

### ISSUE THREAD

**Issue by asjur** [ErikReider/SwaySettings#7]
Getting the following error after installing from AUR

~/.config/sway ❯ swaysettings                                                                                        09:25:03
COULD NOT FIND CONFIG FILE! REINSTALL THE PACKAGE!

**Comment by ErikReider** [comment]
I'm on it! 😃

**Comment by ErikReider** [comment]
@asjur I'm guessing that you don't have my other package [swaync](https://github.com/ErikReider/SwayNotificationCenter) installed?

**Comment by ErikReider** [comment]
Should be fixed now 415fd43bd6531a6a2013c2ec22592f57c1cc81df 😄
